name: Build main.exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc

    - name: Compile main.c
      shell: bash
      run: |
        gcc main.c -o main.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: main-exe
        path: ./main.exe
